##
## EPITECH PROJECT, 2024
## GroundHog
## File description:
## Makefile
##

NAME    =   zappy_gui

$(NAME):

all:	$(NAME)

CFLAGS = -W -Wall -Wextra

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all

.PHONY: all clean fclean re