##
## EPITECH PROJECT, 2024
## GroundHog
## File description:
## Makefile
##

NAME    =   zappy_ai

$(NAME):
	@cp src/ai.py $(NAME)
	@chmod 755 $(NAME)

all:	$(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all

.PHONY: all clean fclean re